"""empty message

Revision ID: 067464631e5b
Revises: 44eb260d9be9
Create Date: 2025-06-08 01:44:07.027856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067464631e5b'
down_revision = '44eb260d9be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_games', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('saved_games')

    # ### end Alembic commands ###
