"""empty message

Revision ID: 44eb260d9be9
Revises: 0763d677d453
Create Date: 2025-06-04 07:32:37.821657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44eb260d9be9'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about')

    # ### end Alembic commands ###
